# -*- coding: utf-8 -*-
"""003 Gradient Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ZqKS09wjURD_dTt2Z-2zTp59fwgrlai
"""

import numpy as np
import matplotlib.pyplot as plt

# -----------------------------
# 1. Generate synthetic data
# -----------------------------
np.random.seed(42)                    # For reproducible results
X = 2 * np.random.rand(100)           # 100 random points between 0 and 2
y = 4 + 3 * X + np.random.randn(100)  # True relationship: y = 4 + 3x + noise

# -----------------------------
# 2. Initialize parameters
# -----------------------------
m = 0.0   # initial slope
b = 0.0   # initial intercept

# -----------------------------
# 3. Hyperparameters
# -----------------------------
lr = 0.1        # learning rate (step size)
epochs = 50     # number of training iterations
N = len(X)      # number of data points

# Lists to store parameter updates and loss
m_history = []
b_history = []
loss_history = []

# -----------------------------
# 4. Gradient Descent Loop
# -----------------------------
for epoch in range(epochs):

    # Predict y using current m and b
    y_pred = m * X + b

    # Calculate error
    error = y_pred - y

    # Compute gradients (derivatives of loss function)
    dm = (2/N) * np.dot(error, X)   # derivative w.r.t m
    db = (2/N) * np.sum(error)      # derivative w.r.t b

    # Update parameters
    m = m - lr * dm
    b = b - lr * db

    # Compute loss (MSE)
    loss = (error**2).mean()

    # Store history for plotting
    m_history.append(m)
    b_history.append(b)
    loss_history.append(loss)

    # Print progress
    print(f"Epoch {epoch+1:02d} | m = {m:.4f}, b = {b:.4f}, loss = {loss:.4f}")

# -----------------------------
# 5. Plot the fitted line
# -----------------------------
plt.scatter(X, y, label="Data Points")
plt.plot(X, m * X + b, color='red', label="Fitted Line")
plt.xlabel("X")
plt.ylabel("y")
plt.title("Linear Regression with Gradient Descent")
plt.legend()
plt.show()

# -----------------------------
# 6. Plot loss curve (optional)
# -----------------------------
plt.plot(loss_history)
plt.xlabel("Epoch")
plt.ylabel("Loss (MSE)")
plt.title("Loss Decrease Over Time")
plt.grid(True)
plt.show()